### ISSUE TITLE
Clean UP & Dockerization eos24jm

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos24jm#4]

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron, 
This model seems already updated. The api is set to run, it has the run.sh file.  The docker builds were run yesterday and it has both images(amd64 and arm64)
![image](https://github.com/ersilia-os/eos24jm/assets/30192291/57288f51-5108-46d7-8e41-ecc66d1666c7)

I tested it using [Colab](https://colab.research.google.com/drive/1DemQ3fHzqoTK_Nxjgqy8IlOyWMbkvStq?usp=sharing) and it works well.
- [eos24jm_colab_fetch.log](https://github.com/ersilia-os/eos24jm/files/11882935/eos24jm_colab_fetch.log)
- [eos24jm_colab_output.csv](https://github.com/ersilia-os/eos24jm/files/11882934/eos24jm_colab_output.csv)

I will test it using CLI and Docker and probably have this issue closed.
